import { NextPage } from "next";
import Head from "next/head";
import Page from "./Page";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>porto-ariq</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <Page></Page>
    </>
  );
};

export default Index;
